---
- name: Configure Web Servers
  hosts: web_servers
  become: yes
  vars:
    app_name: "devops-demo-app"
    web_root: "/var/www/html"

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
      tags: update

    - name: Install Apache Web Server and dependencies
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - mod_ssl
          - git
        state: present
      tags: install

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes
      tags: service

    - name: Deploy sample web application
      copy:
        dest: "{{ web_root }}/index.php"
        content: |
          <?php
          $hostname = gethostname();
          $ip = $_SERVER['SERVER_ADDR'];
          ?>
          <!DOCTYPE html>
          <html>
          <head>
              <title>DevOps Assessment - Web Application</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      height: 100vh;
                      margin: 0;
                  }
                  .container {
                      background: rgba(255,255,255,0.1);
                      padding: 40px;
                      border-radius: 15px;
                      box-shadow: 0 8px 32px rgba(0,0,0,0.3);
                      text-align: center;
                  }
                  h1 { font-size: 2.5em; margin-bottom: 20px; }
                  .info { font-size: 1.2em; margin: 10px 0; }
                  .badge {
                      background: rgba(255,255,255,0.2);
                      padding: 10px 20px;
                      border-radius: 25px;
                      display: inline-block;
                      margin: 10px;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 AWS DevOps Assessment</h1>
                  <div class="info">
                      <div class="badge">Server: <?php echo $hostname; ?></div>
                      <div class="badge">IP: <?php echo $ip; ?></div>
                      <div class="badge">Status: ✅ Running</div>
                  </div>
                  <p style="margin-top: 30px;">Deployed via Terraform + Ansible + CI/CD</p>
              </div>
          </body>
          </html>
        owner: apache
        group: apache
        mode: '0644'
      tags: deploy
      notify: restart apache

    - name: Create health check endpoint
      copy:
        dest: "{{ web_root }}/health.php"
        content: |
          <?php
          header('Content-Type: application/json');
          echo json_encode(['status' => 'healthy', 'timestamp' => date('c'), 'hostname' => gethostname()]);
          ?>
        owner: apache
        group: apache
        mode: '0644'
      tags: deploy

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
